//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Xtra/Control/NewControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewControls"",
    ""maps"": [
        {
            ""name"": ""PLAYER"",
            ""id"": ""20486ec7-27c0-46b7-983a-83831f218c07"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""0f987dee-d861-47f7-b2c3-a3184b20e82a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement_Axis_LEFT"",
                    ""type"": ""Value"",
                    ""id"": ""c548b493-4d9d-4e2a-ac5c-3c99c37579e7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement_Axis_LEFT_Button"",
                    ""type"": ""Button"",
                    ""id"": ""39559882-0110-4800-8713-6c47d9887c1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Value"",
                    ""id"": ""8324cb40-b0e9-4427-b439-db76aca23207"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a0d9ff1d-7502-42e8-b8f9-2d66b2467c98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sword"",
                    ""type"": ""Button"",
                    ""id"": ""613b6ebb-d295-4ced-bce8-dbed5f663aea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Magnesis"",
                    ""type"": ""Button"",
                    ""id"": ""cecb5c8a-145e-4ac2-95eb-e58675ea10dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interactuar"",
                    ""type"": ""Button"",
                    ""id"": ""b099fc29-50a4-4d8a-9273-0bc1437e21c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventary"",
                    ""type"": ""Button"",
                    ""id"": ""6320f0a3-335e-4da3-92ba-ceabdeed8f22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""POWER_EXECUTE"",
                    ""type"": ""Button"",
                    ""id"": ""649ea7b1-44f8-40f9-a2f3-9f335667d039"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""POWER_Left"",
                    ""type"": ""Button"",
                    ""id"": ""8c485bd3-4402-4fc9-b6c2-dbb44fa4cd5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""POWER_Right"",
                    ""type"": ""Button"",
                    ""id"": ""2186a468-cf85-4424-b191-bce764ae892a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R_button"",
                    ""type"": ""Button"",
                    ""id"": ""4f9af769-3716-485f-a79b-ce84cbe9caee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mapa"",
                    ""type"": ""Button"",
                    ""id"": ""dc717a56-7ab4-4796-abbe-c2c7b215f7b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4fdc2867-b678-4532-8ca8-3acba96e3ee5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7209e661-579c-47e4-8e84-640c9d365742"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a86560ab-e7ad-45ad-8c9f-57bf7b22dd8f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(max=1)"",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a55b63c-dc8b-46fb-a999-571a0b128453"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2120744-9bfc-4b1c-b7bc-30f0862594bd"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94555322-45a4-4af0-b4bd-9b61961b6694"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5c3e7d2-ea02-4505-be20-e7c587c77d78"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a3473f6-88e3-4e34-8ba0-89ed4d4a0203"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a6af959-d239-44f5-bb17-f1d03614127e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01352aa8-d19b-447c-affa-f1a5ca12a9ec"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cce590dc-4158-47a5-86f7-60ee54eed6a7"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cc54c8b-ba3c-443f-9434-213557e4f4ae"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Magnesis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d37f426b-a303-46c0-a2e2-ea917c2a471b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Magnesis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""343ef31a-b1a7-427c-9d7f-f3d98c2ef498"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea838ad6-8887-43ca-b907-c44dd961c307"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e3c5e651-6b23-4f88-b575-db4ad1dcfe45"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""95c9b054-cf89-4d38-b8b6-60e5bfaa43aa"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0c2f34b7-2b4f-43a0-8b86-48785bbbd076"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7dda64b4-8404-4342-a3f3-03ca4502ebe8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6c1973aa-8575-4a29-acfa-beb47080392f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""adbc4cc4-83fb-449a-97fb-48f7bdf0dfa4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""POWER_EXECUTE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8047816-a118-47f1-bf1b-3fafba4d4f37"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""POWER_EXECUTE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ddc76e4-964d-46d8-b5c6-4b3aef8670ed"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""POWER_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06b1f7d0-30d8-43d1-b7e1-0126d7ffcbb0"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""POWER_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d25f920-148b-4d72-8ad9-521b9a7e7f40"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""POWER_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b8e6d6-46b3-411b-91fe-ecb71d704e6b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""POWER_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97ad8422-77bc-487d-9c6e-f1069e390720"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""R_button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc03452c-8901-46dd-a262-fa22fef25f77"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""R_button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e71687e-30ed-4b0b-8555-31d4e8c12953"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Mapa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d292c897-c9f5-42d8-b371-a7f45145f71a"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Mapa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8c71db3-1adc-44bf-9268-a3d39e0113ac"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(max=1)"",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9d341595-0dcd-4627-873f-2e73e958eea7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9e46216b-a294-45eb-bc81-349226325728"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""422b1050-9216-45f8-88e6-c82e8410f3f3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6ebf792f-1fed-417d-8a76-a20a6261d02b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bccf1784-f16a-40db-b97a-3774016ce3dc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""MAGNESIS"",
            ""id"": ""36a64b21-e72e-4b3e-a94c-bcc6385e427f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d83c8c60-24bf-4a67-8039-45b81432b997"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""947275b1-44fe-4f92-87bf-480b5ba6e0ae"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""89f20372-8842-4869-94c3-d9bb6682547d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f595f9e4-dce3-4504-b224-e97e49baff9e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b7839ed0-31a2-4ec4-bf88-35c64711490b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bf82dfd1-6db1-437f-9442-46b79641f4ad"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b51cfe00-222f-4020-b508-392e5e02d7eb"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CONVERSACION"",
            ""id"": ""28cca4f0-2566-48a8-83ce-4058c23c6a20"",
            ""actions"": [
                {
                    ""name"": ""Next"",
                    ""type"": ""Button"",
                    ""id"": ""2693c4d2-7dc1-4db6-91f4-d24a9e7d06f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""cf65a5d2-0188-4756-b023-aebcfd15974a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""60b6dfbe-9617-414f-92fe-78ceae089666"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9aef98d0-5f63-4a15-8c83-f7c2dd7569ee"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd3cf415-0af4-4c1f-9a89-1e0bdaa83e59"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec3dc3c9-dab7-4e09-9311-8a0cc0654852"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""INVENTARIO"",
            ""id"": ""20517a37-5b7e-4c17-9891-de36d1a02a3d"",
            ""actions"": [
                {
                    ""name"": ""MovePanels"",
                    ""type"": ""Value"",
                    ""id"": ""8e7dc2b8-ff40-483a-a313-d8d79a6764d6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveInPanel"",
                    ""type"": ""Value"",
                    ""id"": ""b633f9a1-53f4-45a5-ae0f-770d9f86260d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""4ecc2488-9e83-4868-8e14-edef30028690"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a4fe6881-438c-413a-938c-b74543997a43"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePanels"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""694a2057-cabe-4c96-905c-9e860eb19227"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePanels"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4142e2f0-f1a3-4d4f-a45c-bb6b5d864f90"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MovePanels"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1862110d-6c2f-40f3-888a-d1b417e61df0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInPanel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""63e3cb0e-fd60-44bc-81a3-9686bd3cad46"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveInPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""ec70dc6d-5067-429f-b4c2-d4b16ea8d69d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveInPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""882caee8-d778-4166-98f7-ba1998b5a920"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""026ff8ce-669b-412c-a500-5055f8f9e449"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8f2ea677-04f8-4048-bff1-016b262fd077"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MAPA"",
            ""id"": ""bbdd8e5e-d4ce-4213-a338-24467d041f4a"",
            ""actions"": [
                {
                    ""name"": ""Movement_Axis_LEFT"",
                    ""type"": ""Value"",
                    ""id"": ""2f8b7ae6-0cd7-4173-9e26-a920ee3570b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""77fc6f5b-eb5a-464f-9c02-64586ea15326"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5dbbf792-c28c-408b-80b5-9cef78654b2e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(max=1),InvertVector2"",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d75ea3b4-8ce9-43b3-9297-da694df42e0c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9b89c335-4cc7-4b3a-933e-bd9fa1d71d2a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""15bc4964-1456-443e-a037-59f6ccdec22f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6b06edad-3c1d-48ef-898d-073da41e7cd9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0211abdc-82ec-4622-8582-8bc7e6b141e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement_Axis_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2aae648d-50d2-4802-a054-53291bad8099"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6e8d90a8-ce80-46bb-b197-89f4504b1fea"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0646e208-0ad2-491d-b2f0-6406e6fc13c3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""be6f430c-d989-4e14-ae45-38b3b5944f5b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1c7e4845-ff5a-4e54-a892-3c5cae55765d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5620783c-eab7-4248-9abf-f9d7b146af06"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GAMEPAD"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""GAMEPAD"",
            ""bindingGroup"": ""GAMEPAD"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PLAYER
        m_PLAYER = asset.FindActionMap("PLAYER", throwIfNotFound: true);
        m_PLAYER_Jump = m_PLAYER.FindAction("Jump", throwIfNotFound: true);
        m_PLAYER_Movement_Axis_LEFT = m_PLAYER.FindAction("Movement_Axis_LEFT", throwIfNotFound: true);
        m_PLAYER_Movement_Axis_LEFT_Button = m_PLAYER.FindAction("Movement_Axis_LEFT_Button", throwIfNotFound: true);
        m_PLAYER_Run = m_PLAYER.FindAction("Run", throwIfNotFound: true);
        m_PLAYER_Dash = m_PLAYER.FindAction("Dash", throwIfNotFound: true);
        m_PLAYER_Sword = m_PLAYER.FindAction("Sword", throwIfNotFound: true);
        m_PLAYER_Magnesis = m_PLAYER.FindAction("Magnesis", throwIfNotFound: true);
        m_PLAYER_Interactuar = m_PLAYER.FindAction("Interactuar", throwIfNotFound: true);
        m_PLAYER_Inventary = m_PLAYER.FindAction("Inventary", throwIfNotFound: true);
        m_PLAYER_POWER_EXECUTE = m_PLAYER.FindAction("POWER_EXECUTE", throwIfNotFound: true);
        m_PLAYER_POWER_Left = m_PLAYER.FindAction("POWER_Left", throwIfNotFound: true);
        m_PLAYER_POWER_Right = m_PLAYER.FindAction("POWER_Right", throwIfNotFound: true);
        m_PLAYER_R_button = m_PLAYER.FindAction("R_button", throwIfNotFound: true);
        m_PLAYER_Mapa = m_PLAYER.FindAction("Mapa", throwIfNotFound: true);
        // MAGNESIS
        m_MAGNESIS = asset.FindActionMap("MAGNESIS", throwIfNotFound: true);
        m_MAGNESIS_Move = m_MAGNESIS.FindAction("Move", throwIfNotFound: true);
        // CONVERSACION
        m_CONVERSACION = asset.FindActionMap("CONVERSACION", throwIfNotFound: true);
        m_CONVERSACION_Next = m_CONVERSACION.FindAction("Next", throwIfNotFound: true);
        m_CONVERSACION_Enter = m_CONVERSACION.FindAction("Enter", throwIfNotFound: true);
        // INVENTARIO
        m_INVENTARIO = asset.FindActionMap("INVENTARIO", throwIfNotFound: true);
        m_INVENTARIO_MovePanels = m_INVENTARIO.FindAction("MovePanels", throwIfNotFound: true);
        m_INVENTARIO_MoveInPanel = m_INVENTARIO.FindAction("MoveInPanel", throwIfNotFound: true);
        m_INVENTARIO_Action = m_INVENTARIO.FindAction("Action", throwIfNotFound: true);
        // MAPA
        m_MAPA = asset.FindActionMap("MAPA", throwIfNotFound: true);
        m_MAPA_Movement_Axis_LEFT = m_MAPA.FindAction("Movement_Axis_LEFT", throwIfNotFound: true);
        m_MAPA_Zoom = m_MAPA.FindAction("Zoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PLAYER
    private readonly InputActionMap m_PLAYER;
    private IPLAYERActions m_PLAYERActionsCallbackInterface;
    private readonly InputAction m_PLAYER_Jump;
    private readonly InputAction m_PLAYER_Movement_Axis_LEFT;
    private readonly InputAction m_PLAYER_Movement_Axis_LEFT_Button;
    private readonly InputAction m_PLAYER_Run;
    private readonly InputAction m_PLAYER_Dash;
    private readonly InputAction m_PLAYER_Sword;
    private readonly InputAction m_PLAYER_Magnesis;
    private readonly InputAction m_PLAYER_Interactuar;
    private readonly InputAction m_PLAYER_Inventary;
    private readonly InputAction m_PLAYER_POWER_EXECUTE;
    private readonly InputAction m_PLAYER_POWER_Left;
    private readonly InputAction m_PLAYER_POWER_Right;
    private readonly InputAction m_PLAYER_R_button;
    private readonly InputAction m_PLAYER_Mapa;
    public struct PLAYERActions
    {
        private @NewControls m_Wrapper;
        public PLAYERActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PLAYER_Jump;
        public InputAction @Movement_Axis_LEFT => m_Wrapper.m_PLAYER_Movement_Axis_LEFT;
        public InputAction @Movement_Axis_LEFT_Button => m_Wrapper.m_PLAYER_Movement_Axis_LEFT_Button;
        public InputAction @Run => m_Wrapper.m_PLAYER_Run;
        public InputAction @Dash => m_Wrapper.m_PLAYER_Dash;
        public InputAction @Sword => m_Wrapper.m_PLAYER_Sword;
        public InputAction @Magnesis => m_Wrapper.m_PLAYER_Magnesis;
        public InputAction @Interactuar => m_Wrapper.m_PLAYER_Interactuar;
        public InputAction @Inventary => m_Wrapper.m_PLAYER_Inventary;
        public InputAction @POWER_EXECUTE => m_Wrapper.m_PLAYER_POWER_EXECUTE;
        public InputAction @POWER_Left => m_Wrapper.m_PLAYER_POWER_Left;
        public InputAction @POWER_Right => m_Wrapper.m_PLAYER_POWER_Right;
        public InputAction @R_button => m_Wrapper.m_PLAYER_R_button;
        public InputAction @Mapa => m_Wrapper.m_PLAYER_Mapa;
        public InputActionMap Get() { return m_Wrapper.m_PLAYER; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PLAYERActions set) { return set.Get(); }
        public void SetCallbacks(IPLAYERActions instance)
        {
            if (m_Wrapper.m_PLAYERActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnJump;
                @Movement_Axis_LEFT.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT_Button.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT_Button;
                @Movement_Axis_LEFT_Button.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT_Button;
                @Movement_Axis_LEFT_Button.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMovement_Axis_LEFT_Button;
                @Run.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnRun;
                @Dash.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnDash;
                @Sword.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnSword;
                @Sword.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnSword;
                @Sword.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnSword;
                @Magnesis.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMagnesis;
                @Magnesis.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMagnesis;
                @Magnesis.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMagnesis;
                @Interactuar.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInteractuar;
                @Interactuar.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInteractuar;
                @Interactuar.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInteractuar;
                @Inventary.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInventary;
                @Inventary.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInventary;
                @Inventary.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnInventary;
                @POWER_EXECUTE.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_EXECUTE;
                @POWER_EXECUTE.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_EXECUTE;
                @POWER_EXECUTE.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_EXECUTE;
                @POWER_Left.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Left;
                @POWER_Left.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Left;
                @POWER_Left.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Left;
                @POWER_Right.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Right;
                @POWER_Right.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Right;
                @POWER_Right.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnPOWER_Right;
                @R_button.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnR_button;
                @R_button.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnR_button;
                @R_button.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnR_button;
                @Mapa.started -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMapa;
                @Mapa.performed -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMapa;
                @Mapa.canceled -= m_Wrapper.m_PLAYERActionsCallbackInterface.OnMapa;
            }
            m_Wrapper.m_PLAYERActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Movement_Axis_LEFT.started += instance.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.performed += instance.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.canceled += instance.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT_Button.started += instance.OnMovement_Axis_LEFT_Button;
                @Movement_Axis_LEFT_Button.performed += instance.OnMovement_Axis_LEFT_Button;
                @Movement_Axis_LEFT_Button.canceled += instance.OnMovement_Axis_LEFT_Button;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Sword.started += instance.OnSword;
                @Sword.performed += instance.OnSword;
                @Sword.canceled += instance.OnSword;
                @Magnesis.started += instance.OnMagnesis;
                @Magnesis.performed += instance.OnMagnesis;
                @Magnesis.canceled += instance.OnMagnesis;
                @Interactuar.started += instance.OnInteractuar;
                @Interactuar.performed += instance.OnInteractuar;
                @Interactuar.canceled += instance.OnInteractuar;
                @Inventary.started += instance.OnInventary;
                @Inventary.performed += instance.OnInventary;
                @Inventary.canceled += instance.OnInventary;
                @POWER_EXECUTE.started += instance.OnPOWER_EXECUTE;
                @POWER_EXECUTE.performed += instance.OnPOWER_EXECUTE;
                @POWER_EXECUTE.canceled += instance.OnPOWER_EXECUTE;
                @POWER_Left.started += instance.OnPOWER_Left;
                @POWER_Left.performed += instance.OnPOWER_Left;
                @POWER_Left.canceled += instance.OnPOWER_Left;
                @POWER_Right.started += instance.OnPOWER_Right;
                @POWER_Right.performed += instance.OnPOWER_Right;
                @POWER_Right.canceled += instance.OnPOWER_Right;
                @R_button.started += instance.OnR_button;
                @R_button.performed += instance.OnR_button;
                @R_button.canceled += instance.OnR_button;
                @Mapa.started += instance.OnMapa;
                @Mapa.performed += instance.OnMapa;
                @Mapa.canceled += instance.OnMapa;
            }
        }
    }
    public PLAYERActions @PLAYER => new PLAYERActions(this);

    // MAGNESIS
    private readonly InputActionMap m_MAGNESIS;
    private IMAGNESISActions m_MAGNESISActionsCallbackInterface;
    private readonly InputAction m_MAGNESIS_Move;
    public struct MAGNESISActions
    {
        private @NewControls m_Wrapper;
        public MAGNESISActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MAGNESIS_Move;
        public InputActionMap Get() { return m_Wrapper.m_MAGNESIS; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MAGNESISActions set) { return set.Get(); }
        public void SetCallbacks(IMAGNESISActions instance)
        {
            if (m_Wrapper.m_MAGNESISActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MAGNESISActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MAGNESISActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MAGNESISActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_MAGNESISActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public MAGNESISActions @MAGNESIS => new MAGNESISActions(this);

    // CONVERSACION
    private readonly InputActionMap m_CONVERSACION;
    private ICONVERSACIONActions m_CONVERSACIONActionsCallbackInterface;
    private readonly InputAction m_CONVERSACION_Next;
    private readonly InputAction m_CONVERSACION_Enter;
    public struct CONVERSACIONActions
    {
        private @NewControls m_Wrapper;
        public CONVERSACIONActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Next => m_Wrapper.m_CONVERSACION_Next;
        public InputAction @Enter => m_Wrapper.m_CONVERSACION_Enter;
        public InputActionMap Get() { return m_Wrapper.m_CONVERSACION; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CONVERSACIONActions set) { return set.Get(); }
        public void SetCallbacks(ICONVERSACIONActions instance)
        {
            if (m_Wrapper.m_CONVERSACIONActionsCallbackInterface != null)
            {
                @Next.started -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnNext;
                @Next.performed -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnNext;
                @Next.canceled -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnNext;
                @Enter.started -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_CONVERSACIONActionsCallbackInterface.OnEnter;
            }
            m_Wrapper.m_CONVERSACIONActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Next.started += instance.OnNext;
                @Next.performed += instance.OnNext;
                @Next.canceled += instance.OnNext;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
            }
        }
    }
    public CONVERSACIONActions @CONVERSACION => new CONVERSACIONActions(this);

    // INVENTARIO
    private readonly InputActionMap m_INVENTARIO;
    private IINVENTARIOActions m_INVENTARIOActionsCallbackInterface;
    private readonly InputAction m_INVENTARIO_MovePanels;
    private readonly InputAction m_INVENTARIO_MoveInPanel;
    private readonly InputAction m_INVENTARIO_Action;
    public struct INVENTARIOActions
    {
        private @NewControls m_Wrapper;
        public INVENTARIOActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePanels => m_Wrapper.m_INVENTARIO_MovePanels;
        public InputAction @MoveInPanel => m_Wrapper.m_INVENTARIO_MoveInPanel;
        public InputAction @Action => m_Wrapper.m_INVENTARIO_Action;
        public InputActionMap Get() { return m_Wrapper.m_INVENTARIO; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(INVENTARIOActions set) { return set.Get(); }
        public void SetCallbacks(IINVENTARIOActions instance)
        {
            if (m_Wrapper.m_INVENTARIOActionsCallbackInterface != null)
            {
                @MovePanels.started -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMovePanels;
                @MovePanels.performed -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMovePanels;
                @MovePanels.canceled -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMovePanels;
                @MoveInPanel.started -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMoveInPanel;
                @MoveInPanel.performed -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMoveInPanel;
                @MoveInPanel.canceled -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnMoveInPanel;
                @Action.started -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_INVENTARIOActionsCallbackInterface.OnAction;
            }
            m_Wrapper.m_INVENTARIOActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePanels.started += instance.OnMovePanels;
                @MovePanels.performed += instance.OnMovePanels;
                @MovePanels.canceled += instance.OnMovePanels;
                @MoveInPanel.started += instance.OnMoveInPanel;
                @MoveInPanel.performed += instance.OnMoveInPanel;
                @MoveInPanel.canceled += instance.OnMoveInPanel;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
            }
        }
    }
    public INVENTARIOActions @INVENTARIO => new INVENTARIOActions(this);

    // MAPA
    private readonly InputActionMap m_MAPA;
    private IMAPAActions m_MAPAActionsCallbackInterface;
    private readonly InputAction m_MAPA_Movement_Axis_LEFT;
    private readonly InputAction m_MAPA_Zoom;
    public struct MAPAActions
    {
        private @NewControls m_Wrapper;
        public MAPAActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement_Axis_LEFT => m_Wrapper.m_MAPA_Movement_Axis_LEFT;
        public InputAction @Zoom => m_Wrapper.m_MAPA_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_MAPA; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MAPAActions set) { return set.Get(); }
        public void SetCallbacks(IMAPAActions instance)
        {
            if (m_Wrapper.m_MAPAActionsCallbackInterface != null)
            {
                @Movement_Axis_LEFT.started -= m_Wrapper.m_MAPAActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.performed -= m_Wrapper.m_MAPAActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.canceled -= m_Wrapper.m_MAPAActionsCallbackInterface.OnMovement_Axis_LEFT;
                @Zoom.started -= m_Wrapper.m_MAPAActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_MAPAActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_MAPAActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_MAPAActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement_Axis_LEFT.started += instance.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.performed += instance.OnMovement_Axis_LEFT;
                @Movement_Axis_LEFT.canceled += instance.OnMovement_Axis_LEFT;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public MAPAActions @MAPA => new MAPAActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GAMEPADSchemeIndex = -1;
    public InputControlScheme GAMEPADScheme
    {
        get
        {
            if (m_GAMEPADSchemeIndex == -1) m_GAMEPADSchemeIndex = asset.FindControlSchemeIndex("GAMEPAD");
            return asset.controlSchemes[m_GAMEPADSchemeIndex];
        }
    }
    public interface IPLAYERActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMovement_Axis_LEFT(InputAction.CallbackContext context);
        void OnMovement_Axis_LEFT_Button(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSword(InputAction.CallbackContext context);
        void OnMagnesis(InputAction.CallbackContext context);
        void OnInteractuar(InputAction.CallbackContext context);
        void OnInventary(InputAction.CallbackContext context);
        void OnPOWER_EXECUTE(InputAction.CallbackContext context);
        void OnPOWER_Left(InputAction.CallbackContext context);
        void OnPOWER_Right(InputAction.CallbackContext context);
        void OnR_button(InputAction.CallbackContext context);
        void OnMapa(InputAction.CallbackContext context);
    }
    public interface IMAGNESISActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface ICONVERSACIONActions
    {
        void OnNext(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
    }
    public interface IINVENTARIOActions
    {
        void OnMovePanels(InputAction.CallbackContext context);
        void OnMoveInPanel(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
    }
    public interface IMAPAActions
    {
        void OnMovement_Axis_LEFT(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
